# Package setup

The DESCRIPTION file is created using this code.

```{r package-setup, message=FALSE, results='hide'}
usethis::create_package(
  path = ".",
  fields = list(
    Package = params$package_name,
    Version = "0.0.0.9000",
    Title = "bayesdir",
    Description = "Implements Bayesian directional data analysis for von Mises-Fisher models and related methods.",
    `Authors@R` = person(
      given = "Sheng",
      family = "Jiang",
      email = "jiangsheng@cuhk.edu.cn",
      role = c("aut", "cre")
      )
  )
)



usethis::use_mit_license(copyright_holder = "Sheng Jiang")
```

The following is what will show up when someone types `package?bayesdir` in
the console.

```{package_doc}
#' bayesdir
#'
#' This package implements the `bayesdir` method.
#' 
#' @docType package
```


This package will have some dependancies:

```{r dependencies, message = FALSE}

##library(ggplot2)
##usethis::use_package("tidyverse", type = "depends") 
## usethis::use_package("ggplot2")
usethis::use_package("ggplot2", type = "imports")
usethis::use_package("MASS", type = "imports")
usethis::use_package("parallel", type = "imports")
usethis::use_package("stats", type = "imports")
usethis::use_package("rstiefel", type = "imports")
usethis::use_package("tidyverse", type = "imports")

usethis::use_pipe(export=TRUE)
```

```{r, send_to = 'R/imports.R'}
#' @importFrom parallel mclapply
#' @importFrom stats quantile rnorm sd uniroot
#' @importFrom rstiefel rmf.vector
NULL
```




<!-- library("tmvnsim") ## for tmvnsim -->
<!-- library("MASS") ## for mvrnorm -->
<!-- library("scatterplot3d") # for 3d plot  -->
<!-- library("RColorBrewer") ## distinct colors  -->
<!-- library("matrixsampling") ## r-inverse Wishart -->
<!-- library("matrixNormal") ## matrix normal random elements  -->
<!-- library("pgdraw") ## draw PG r.v.'s  -->
<!-- library("parallel") ## mc-mapply -->
<!-- library("svMisc") -->
<!-- library("mclust") ## for warm start  -->
<!-- library("plotly") -->
<!-- library("ggcorrplot") -->

<!-- library("Rfast") -->
<!-- library("Rfast2") -->
